### ISSUE TITLE
Support `rank` and `select` operations?

### ISSUE THREAD

**Issue by vaibhavsagar** [recursion-ninja/bv-little#3]
It would be wonderful to use these bitvectors as rank/select dictionaries.

**Comment by recursion-ninja** [comment]
This should be doable based on my reading of [this description][1] of the operations.

I'll explore whether an additional data structure will need to be added to the bit vector type maintained after each mutable operation, or if the auxiliary structure can be created as needed when `rank` or `select` are called on the bitvector.

I won't have a lot of free time to implement this for a while. If you're interested in implementing a pull request, it would be welcomed.

[1]: https://en.m.wikipedia.org/wiki/Succinct_data_structure

**Comment by vaibhavsagar** [comment]
I think the current state of the art is http://www.cs.cmu.edu/~./dongz/papers/poppy.pdf. There's an implementation of this at https://github.com/Gabriel439/Haskell-Succinct-Vector-Library.

**Comment by recursion-ninja** [comment]
I apologize for the delay @vaibhavsagar , I've had other priorities the last few months. I have implemented the `rank` & `select` functions on the [`rank-select`][0] branch. Please take a look at the new functionality.

The functions currently have the following type signatures: 

    rank :: BitVector -> Word -> Word
    select :: BitVector -> Word -> Maybe Word

Both employ "broadword programming" for their implementation and do not allocate any additional memory structures within the `BitVector` data type. The advantage of this technique is that there is no additional memory overhead for users that do not require the `BitVector` to be a succinct data structure. The downside is that `rank` and `select` are not as efficient as possible (*O(1)* time). It's important for me and our use-case at AMNH that the `BitVector` type not allocate any more memory than required for our functionality.

I did consider the following functions instead:

    succinctDictionary :: BitVector -> SuccinctDictionary
    rank :: Maybe SuccinctDictionary -> BitVector -> Word -> Word
    select :: Maybe SuccinctDictionary -> BitVector -> Word -> Maybe Word

With this interface, a `Nothing :: Maybe SuccinctDictionary` indicates to use the "broadword programming" technique for efficiency reason. A `Just v :: Maybe SuccinctDictionary` value indicates using the precomputed `SuccinctDictionary` for the `BitVectory` because either the `BitVector` is so long it requires the dictionary for efficiency, or enough `rank/`select` operations will be performed on *this* `BitVector` that pre-computing the dictionary is worth the time and space investment.

There are advantages of this "interface." Notably, it allows for the creation of a `SuccinctDictionary` for users who require the `BitVector` type to be a succinct data structure in an "opt-in" manner. Additionally, this "interface" would allow for the implementation of `rank` & `select` that are truly *O(1)*. The downside is that the `SuccinctDictionary` for a given `BitVector` will have to be manually tracked by the user. A second "downside" is that the algorithms described for constructing the succinct dictionaries are quite finicky, so it would require more time to implement than what I have done currently with the "broadword programming" technique. Finally literature has references that for small succinct data structures, "broadword programming" tends to outperform the use of succinct dictionaries until the size of the `BitVector` scales very large.

I'm open to merging and uploading what I have now to `hackage`. However, if you're interested in creating a pull request for an implementation along the lines of the second interface I just described, I'm open to the contribution.

Let me know what you think about the current implementation and the possible pull request.

[0]: https://github.com/recursion-ninja/bv-little/tree/rank-select

**Comment by vaibhavsagar** [comment]
This looks great, thank you for implementing it!

**Comment by recursion-ninja** [comment]
> I'm not sure I'll have time to contribute a pull request using succinct dictionaries anytime soon, unfortunately frowning.

@vaibhavsagar  you and me both!

I'll merge this branch into [`master`][0], tag a new release, and upload to hackage tomorrow.

[0]: https://github.com/recursion-ninja/bv-little/tree/master

**Comment by recursion-ninja** [comment]
New release is up. See 34ef18bde3d220870148127ff7325d37f700b51a for the [`1.1.0`](https://github.com/recursion-ninja/bv-little/releases/tag/v1.1.0) tag.

**Comment by vaibhavsagar** [comment]
Thank you!
